[project]
name = "debloat-apps-optimizer"
version = "0.1.0"
description = "Tweaks for apps in Windows..."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "psutil>=7.0.0",
    "pystray>=0.19.5",
    "watchdog>=6.0.0",
]
